"""English UI strings (partial — extend as needed)."""

STRINGS = {
    'app.title': 'Fishing Store POS',

    'common.search': 'Search:',
    'common.clear': 'Clear',
    'common.attention': 'Attention',
    'common.error': 'Error',
    'common.success': 'Success',
    'common.confirm': 'Confirm',
    'common.export': 'Export',
    'common.ready': 'Done',
    'common.save': 'Save',
    'common.cancel': 'Cancel',
    'common.unknown': 'Unknown',
    'common.dash': '—',
    'common.checkbox_header': '☐',

    'main.btn.cash': 'Cash register',
    'main.btn.warehouse': 'Warehouse',
    'main.btn.checks': 'Receipts (returns)',
    'main.btn.analysis': 'Analysis',
    'main.close_confirm': 'Child windows are open. Close the application?',

    'warehouse.title': 'Warehouse',
    'warehouse.col.id': 'ID',
    'warehouse.col.code': 'Product code',
    'warehouse.col.name': 'Name',
    'warehouse.col.buy_price': 'Purchase price',
    'warehouse.col.sale_price': 'Sale price',
    'warehouse.col.amount': 'Quantity',
    'warehouse.col.purchase_date': 'Purchase date',
    'warehouse.col.supplier': 'Supplier',
    'warehouse.btn.add': 'Add product',
    'warehouse.btn.edit_selected': 'Edit selected',
    'warehouse.btn.write_off': 'Write off',
    'warehouse.btn.refresh': 'Refresh',
    'warehouse.btn.delete': 'Delete selected',
    'warehouse.btn.export': 'Export to Excel',
    'warehouse.filter.available': 'In stock',
    'warehouse.filter.not_available': 'Out of stock',
    'warehouse.edit_no_selection': 'Check items or select a row to edit.',
    'warehouse.write_off_select_one': 'Select one product to write off.',
    'warehouse.delete_no_selection': 'Check products to delete (☐ column).',
    'warehouse.delete_confirm': 'Delete {count} products?\n{preview}',
    'warehouse.delete_error': 'Failed to delete product: {error}',
    'warehouse.export_sheet': 'Warehouse',
    'warehouse.export_filename': 'Warehouse_{date}.xlsx',
    'warehouse.export_no_data': 'No data to export.',
    'warehouse.export_saved': 'File saved:\n{path}',

    'cash.title': 'Cash register',
    'cash.cart_title': 'Cart',
    'cash.col.code': 'Code',
    'cash.col.name': 'Name',
    'cash.col.price': 'Sale price',
    'cash.col.stock': 'In stock',
    'cash.col.qty': 'Qty',
    'cash.col.sum': 'Sum',
    'cash.qty_label': 'Quantity:',
    'cash.btn.add': 'Add to cart (Enter)',
    'cash.btn.checkout': 'Checkout',
    'cash.btn.remove': 'Remove',
    'cash.total': 'Total: {sum}',
    'cash.select_product': 'Select a product to add.',
    'cash.product_not_found': 'Product not found.',
    'cash.qty_positive': 'Quantity must be positive.',
    'cash.not_enough_stock': 'Not enough in stock. Available: {amount}',
    'cash.out_of_stock': 'Product is out of stock.',
    'cash.select_cart_item': 'Select an item in the cart.',
    'cash.empty_cart': 'Cart is empty.',
    'cash.delete_zero_qty': 'Quantity is 0. Remove item from cart?',
    'cash.delete_title': 'Remove',

    'payment.title': 'Payment',
    'payment.total': 'Amount due: {sum}',
    'payment.type_label': 'Payment type:',
    'payment.payed_label': 'Amount paid:',
    'payment.btn.pay': 'Pay',
    'payment.btn.view_receipt': 'View receipt',
    'payment.too_small': 'Paid amount is less than total.',
    'payment.failed': 'Payment failed: {error}',
    'payment.success': 'Payment successful. Change: {change}',
    'payment.no_check': 'Receipt not created yet.',
    'payment.no_receipt_text': 'Receipt text not found.',

    'checks.title': 'Receipts (returns)',
    'checks.col.id': 'ID',
    'checks.col.date': 'Date',
    'checks.col.status': 'Status',
    'checks.col.payment_type': 'Payment type',
    'checks.col.sum': 'Sum',
    'checks.col.payed': 'Paid',
    'checks.col.refused': 'Refunded',
    'checks.product.name': 'Name',
    'checks.product.code': 'Code',
    'checks.product.amount': 'Quantity',
    'checks.product.price': 'Price',
    'checks.product.total': 'Total',
    'checks.btn.return_selected': 'Return selected',
    'checks.btn.return_all': 'Return entire receipt',
    'checks.btn.open_receipt': 'Open receipt',
    'checks.select_check': 'Select a receipt.',
    'checks.select_products': 'Check products to return (☐ column).',
    'checks.not_found': 'Receipt not found.',
    'checks.return_success': 'Return receipt #{id} created for {sum}.',
    'checks.return_qty_title': 'Change quantity',
    'checks.return_qty_prompt': 'Return quantity (max {max}):',
    'check.status.pending': 'Awaiting payment',
    'check.status.sale': 'Sale',
    'check.status.return': 'Return',
    'check.status.writeoff': 'Write-off',
    'check.status.unknown': 'Unknown',

    'analysis.title': 'Sales analysis',
    'analysis.period_from': 'From:',
    'analysis.period_to': 'to:',
    'analysis.btn.refresh': 'Refresh',
    'analysis.btn.export': 'Export to Excel',
    'analysis.col.last_sale': 'Last sale date',
    'analysis.col.code': 'Product code',
    'analysis.col.name': 'Name',
    'analysis.col.sold_qty': 'Sold qty',
    'analysis.col.returned_qty': 'Returned qty',
    'analysis.col.net_qty': 'Net qty',
    'analysis.col.stock': 'Stock',
    'analysis.col.sold_sum': 'Sales sum',
    'analysis.col.returned_sum': 'Returns sum',
    'analysis.col.net_sum': 'Net sum',
    'analysis.date_range_error': 'Start date cannot be after end date.',
    'analysis.total_earned': 'Total earned: {sum}',
    'analysis.top_sold': 'Top sold: Code {code}, {name}, Qty: {qty}',
    'analysis.top_earned': 'Top revenue: Code {code}, {name}, Sum: {sum}',
    'analysis.top_sold_empty': 'Top sold: —',
    'analysis.top_earned_empty': 'Top revenue: —',
    'analysis.export_sheet': 'Sales analysis',
    'analysis.export_filename': 'Report_{date}.xlsx',
    'analysis.no_data': 'No data to export.',
    'analysis.export_saved': 'File saved:\n{path}',

    'product_edit.title.add': 'Add product',
    'product_edit.title.edit': 'Edit product',
    'product_edit.label.name': 'Name:',
    'product_edit.label.code': 'Product code:',
    'product_edit.label.buy_price': 'Purchase price:',
    'product_edit.label.sale_price': 'Sale price:',
    'product_edit.label.amount': 'Quantity:',
    'product_edit.label.purchase_date': 'Purchase date:',
    'product_edit.label.supplier': 'Supplier:',
    'product_edit.empty_date': 'Leave empty',
    'product_edit.btn.add_more': 'Add another',
    'product_edit.invalid_numbers': 'Invalid number format',
    'product_edit.empty_name': 'Name cannot be empty',
    'product_edit.negative_values': 'Values cannot be negative',
    'product_edit.added_continue': 'Product added. You can enter the next one.',

    'write_off.title': 'Write off product',
    'write_off.info_group': 'Product info',
    'write_off.field.stock': 'In stock:',
    'write_off.field.supplier': 'Supplier:',
    'write_off.qty_label': 'Quantity to write off:',
    'write_off.btn.submit': 'Write off',
    'write_off.product_not_found': 'Product not found.',
    'write_off.invalid_qty': 'Enter a valid quantity.',
    'write_off.qty_zero': 'Quantity must be greater than 0.',
    'write_off.success': 'Written off. Receipt #{id}.',
    'write_off.failed': 'Write-off failed: {error}',

    'receipt.title': 'Receipt #{id}',
    'receipt.btn.print': 'Print (Ctrl+P)',
    'receipt.btn.save': 'Save (Ctrl+S)',
    'receipt.btn.close': 'Close (Space/Enter)',
    'receipt.save_title': 'Save',
    'receipt.folder_name': 'Receipts',
    'receipt.pdf_filename': 'Receipt {id}_{time}.pdf',
    'receipt.no_fpdf': 'fpdf2 is not installed.\nRun: pip install fpdf2',
    'receipt.save_error': 'Failed to save PDF:\n{error}',
    'receipt.save_success': 'Receipt saved:\n{path}',
    'receipt.print_error': 'Failed to print:\n{error}',
}

PAYMENT_TYPES = {
    'cash': 'Cash',
    'card': 'Card',
    'wallet': 'E-wallet',
}
