"""Русские строки интерфейса."""

STRINGS = {
    # ── Приложение ──
    'app.title': 'Учёт и торговля рыболовными товарами',

    # ── Общие ──
    'common.search': 'Поиск:',
    'common.clear': 'Очистить',
    'common.attention': 'Внимание',
    'common.error': 'Ошибка',
    'common.success': 'Успех',
    'common.confirm': 'Подтверждение',
    'common.export': 'Экспорт',
    'common.ready': 'Готово',
    'common.save': 'Сохранить',
    'common.cancel': 'Отмена',
    'common.unknown': 'Неизвестно',
    'common.dash': '—',
    'common.checkbox_header': '☐',

    # ── Главное окно ──
    'main.btn.cash': 'Касса',
    'main.btn.warehouse': 'Склад',
    'main.btn.checks': 'Просмотр чеков (возврат)',
    'main.btn.analysis': 'Анализ',
    'main.close_confirm': (
        'Открыты дочерние окна. Вы уверены, что хотите закрыть приложение?'
    ),

    # ── Склад ──
    'warehouse.title': 'Склад',
    'warehouse.col.id': 'ID',
    'warehouse.col.code': 'Код товара',
    'warehouse.col.name': 'Наименование',
    'warehouse.col.buy_price': 'Цена закупки',
    'warehouse.col.sale_price': 'Цена продажи',
    'warehouse.col.amount': 'Количество',
    'warehouse.col.purchase_date': 'Дата закупки',
    'warehouse.col.supplier': 'Поставщик',
    'warehouse.btn.add': 'Добавить товар',
    'warehouse.btn.edit_selected': 'Редактировать выбранные',
    'warehouse.btn.write_off': 'Списать',
    'warehouse.btn.refresh': 'Обновить',
    'warehouse.btn.delete': 'Удалить выбранное',
    'warehouse.btn.export': 'Экспорт в Excel',
    'warehouse.filter.available': 'В наличии',
    'warehouse.filter.not_available': 'Закончившиеся',
    'warehouse.edit_no_selection': (
        'Отметьте товары галочками или выберите строку для редактирования.'
    ),
    'warehouse.write_off_select_one': 'Выберите один товар для списания.',
    'warehouse.delete_no_selection': 'Отметьте товары для удаления (колонка ☐).',
    'warehouse.delete_confirm': 'Удалить {count} товаров?\n{preview}',
    'warehouse.delete_error': 'Не удалось удалить товар: {error}',
    'warehouse.export_sheet': 'Склад',
    'warehouse.export_filename': 'Склад_{date}.xlsx',
    'warehouse.export_no_data': 'Нет данных для экспорта.',
    'warehouse.export_saved': 'Файл сохранён:\n{path}',

    # ── Касса ──
    'cash.title': 'Касса',
    'cash.cart_title': 'Корзина',
    'cash.col.code': 'Код',
    'cash.col.name': 'Наименование',
    'cash.col.price': 'Цена продажи',
    'cash.col.stock': 'На складе',
    'cash.col.qty': 'Кол-во',
    'cash.col.sum': 'Сумма',
    'cash.qty_label': 'Количество:',
    'cash.btn.add': 'Добавить в корзину (Enter)',
    'cash.btn.checkout': 'Оформить продажу',
    'cash.btn.remove': 'Удалить',
    'cash.total': 'Итого: {sum}',
    'cash.select_product': 'Выберите товар для добавления.',
    'cash.product_not_found': 'Товар не найден.',
    'cash.qty_positive': 'Количество должно быть положительным.',
    'cash.not_enough_stock': 'Недостаточно на складе. Доступно: {amount}',
    'cash.out_of_stock': 'Товар закончился на складе.',
    'cash.select_cart_item': 'Выберите товар в корзине.',
    'cash.empty_cart': 'Корзина пуста.',
    'cash.delete_zero_qty': 'Количество стало 0. Удалить товар из корзины?',
    'cash.delete_title': 'Удаление',

    # ── Оплата ──
    'payment.title': 'Оплата',
    'payment.total': 'Сумма к оплате: {sum}',
    'payment.type_label': 'Тип оплаты:',
    'payment.payed_label': 'Внесенная сумма:',
    'payment.btn.pay': 'Оплатить',
    'payment.btn.view_receipt': 'Просмотр чеков',
    'payment.too_small': 'Внесенная сумма меньше суммы к оплате.',
    'payment.failed': 'Не удалось провести оплату: {error}',
    'payment.success': 'Оплата прошла успешно. Сдача: {change}',
    'payment.no_check': 'Чек ещё не создан.',
    'payment.no_receipt_text': 'Текст чека не найден.',

    # ── Чеки ──
    'checks.title': 'Просмотр чеков (возврат)',
    'checks.col.id': 'ID',
    'checks.col.date': 'Дата',
    'checks.col.status': 'Статус',
    'checks.col.payment_type': 'Тип оплаты',
    'checks.col.sum': 'Сумма',
    'checks.col.payed': 'Внесено',
    'checks.col.refused': 'Возвращено',
    'checks.product.name': 'Название',
    'checks.product.code': 'Код',
    'checks.product.amount': 'Количество',
    'checks.product.price': 'Цена',
    'checks.product.total': 'Стоимость',
    'checks.btn.return_selected': 'Возврат выбранных',
    'checks.btn.return_all': 'Возврат всего чека',
    'checks.btn.open_receipt': 'Открыть чек',
    'checks.select_check': 'Выберите чек.',
    'checks.select_products': 'Отметьте товары для возврата (колонка ☐).',
    'checks.not_found': 'Чек не найден.',
    'checks.return_success': 'Создан чек возврата №{id} на сумму {sum}.',
    'checks.return_qty_title': 'Изменить количество',
    'checks.return_qty_prompt': 'Введите количество для возврата (макс {max}):',
    'check.status.pending': 'Ожидание оплаты',
    'check.status.sale': 'Покупка',
    'check.status.return': 'Возврат',
    'check.status.writeoff': 'Списание',
    'check.status.unknown': 'Неизвестно',

    # ── Анализ ──
    'analysis.title': 'Анализ продаж',
    'analysis.period_from': 'Период с:',
    'analysis.period_to': 'по:',
    'analysis.btn.refresh': 'Обновить',
    'analysis.btn.export': 'Экспорт в Excel',
    'analysis.col.last_sale': 'Дата последней продажи',
    'analysis.col.code': 'Код товара',
    'analysis.col.name': 'Наименование',
    'analysis.col.sold_qty': 'Продано шт.',
    'analysis.col.returned_qty': 'Возврат шт.',
    'analysis.col.net_qty': 'Итого шт.',
    'analysis.col.stock': 'Остаток на складе',
    'analysis.col.sold_sum': 'Сумма продаж',
    'analysis.col.returned_sum': 'Сумма возвратов',
    'analysis.col.net_sum': 'Итого сумма',
    'analysis.date_range_error': 'Дата начала не может быть позже даты конца.',
    'analysis.total_earned': 'Всего заработано: {sum}',
    'analysis.top_sold': 'Самый продаваемый товар: Код {code}, {name}, Кол-во: {qty}',
    'analysis.top_earned': 'Товар с наибольшей выручкой: Код {code}, {name}, Сумма: {sum}',
    'analysis.top_sold_empty': 'Самый продаваемый товар: —',
    'analysis.top_earned_empty': 'Товар с наибольшей выручкой: —',
    'analysis.export_sheet': 'Анализ продаж',
    'analysis.export_filename': 'Отчет_{date}.xlsx',
    'analysis.no_data': 'Нет данных для экспорта.',
    'analysis.export_saved': 'Файл сохранён:\n{path}',

    # ── Редактирование товара ──
    'product_edit.title.add': 'Добавление товара',
    'product_edit.title.edit': 'Редактирование товара',
    'product_edit.label.name': 'Наименование:',
    'product_edit.label.code': 'Код товара:',
    'product_edit.label.buy_price': 'Цена закупки:',
    'product_edit.label.sale_price': 'Цена продажи:',
    'product_edit.label.amount': 'Количество:',
    'product_edit.label.purchase_date': 'Дата закупки:',
    'product_edit.label.supplier': 'Поставщик:',
    'product_edit.empty_date': 'Оставить пустым',
    'product_edit.btn.add_more': 'Добавить ещё',
    'product_edit.invalid_numbers': 'Неверный формат числовых полей',
    'product_edit.empty_name': 'Наименование не может быть пустым',
    'product_edit.negative_values': 'Числовые значения не могут быть отрицательными',
    'product_edit.added_continue': 'Товар добавлен. Можно вводить следующий.',

    # ── Списание ──
    'write_off.title': 'Списание товара',
    'write_off.info_group': 'Информация о товаре',
    'write_off.field.stock': 'На складе:',
    'write_off.field.supplier': 'Поставщик:',
    'write_off.qty_label': 'Количество для списания:',
    'write_off.btn.submit': 'Списать',
    'write_off.product_not_found': 'Товар не найден.',
    'write_off.invalid_qty': 'Введите корректное количество.',
    'write_off.qty_zero': 'Укажите количество больше 0.',
    'write_off.success': 'Товар списан. Чек №{id}.',
    'write_off.failed': 'Не удалось списать товар: {error}',

    # ── Чек (просмотр) ──
    'receipt.title': 'Чек №{id}',
    'receipt.btn.print': 'Печать (Ctrl+P)',
    'receipt.btn.save': 'Сохранить (Ctrl+S)',
    'receipt.btn.close': 'Закрыть (Пробел/Enter)',
    'receipt.save_title': 'Сохранение',
    'receipt.folder_name': 'Чеки',
    'receipt.pdf_filename': 'Чек {id}_{time}.pdf',
    'receipt.no_fpdf': (
        'Не установлена библиотека fpdf2.\n'
        'Установите её командой: pip install fpdf2'
    ),
    'receipt.save_error': 'Не удалось сохранить PDF:\n{error}',
    'receipt.save_success': 'Чек сохранён:\n{path}',
    'receipt.print_error': 'Не удалось отправить на печать:\n{error}',
}

PAYMENT_TYPES = {
    'cash': 'Наличные',
    'card': 'Карта',
    'wallet': 'Электронный кошелек',
}
